version: "3"

services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ MONGO_INITDB_ROOT_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ MONGO_INITDB_ROOT_PASSWORD }}"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
      - data:/data/db

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "{{ application_prisma_port }}:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://{{ MONGO_INITDB_ROOT_USERNAME }}:{{ MONGO_INITDB_ROOT_PASSWORD }}@mongo
            port: 27017

  api:
    image: "{{ application_api_image }}:{{ application_api_tag }}"
    restart: always
    working_dir: /app
    depends_on:
      - prisma
      - mongo
    ports:
      - "{{ application_api_port }}:3000"
    environment:
      PRISMA_SECRET: "{{ PRISMA_SECRET }}"
      PORT: "{{ application_api_port }}"
      FRONT_URL: "{{ application_scheme }}://{{ ansible_host }}"
      STRIPE_SECRET_KEY: "{{ STRIPE_SECRET_KEY }}"
      APP_SECRET: "{{ APP_SECRET }}"
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      GOOGLE_MAPS_API_KEY: "{{ GOOGLE_MAPS_API_KEY }}"
    entrypoint: /app/entrypoint.sh
    command: yarn start

  bo:
    image: "{{ application_backoffice_image }}:{{ application_backoffice_tag }}"
    ports:
      - "{{ application_backoffice_port }}:80"

volumes:
  mongo: ~
  data: ~
