name: Master

on: 
  push:
    branches:
      - master
      - publish-app

env:
  VAULT_PASS: ${{ secrets.VAULT_PASS }}

jobs:
  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setenv
      - run: ansible-playbook get_elb_dns.yml -i inventory/hosts
      - run: echo "::set-env name=REACT_APP_API_URL::$(cat elb_api_dns.txt)"
      - uses: actions/setup-node@v2-beta
      - run: yarn install
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - run: yarn expo login --non-interactive -u ${{ env.EXPO_USERNAME }} -p ${{ env.EXPO_PASSWORD }}
      - run: yarn expo publish --non-interactive
  
  back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: automation/ansible
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setenv
      - name: Build Api image
        uses: docker/build-push-action@v1
        with:
          path: ./api
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_api
          tags: latest
      - name: Build Back-office image
        uses: docker/build-push-action@v1
        with:
          path: ./back-office
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_back-office
          build_args: REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: latest
      - run: echo $SSH_PRIVATE_KEY > ~/id_rsa
      - run: chmod 600 ~/id_rsa
      - run: ansible-galaxy install -r requirements.yml
      - run: chmod 777 inventory/ec2.py
      - name: Deploy Api and Back-office
        run: |
          ansible-playbook -i inventory/ec2.py staging.yml --tags deploy -u ubuntu --key ~/id_rsa
