name: Master

on: 
  push:
    branches:
      - master
      - publish-app

env:
  VAULT_PASS: ${{ secrets.VAULT_PASS }}

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install and setup env
        run: |
          pip install ansible boto
          .github/actions/setenv/entrypoint.sh
      - name: Get API url
        working-directory: automation/ansible
        run: |
          ansible-playbook get_elb_dns.yml -i inventory/hosts
          echo "::set-env name=REACT_APP_API_URL::$(cat elb_api_dns.txt)"
      - uses: actions/setup-node@v2-beta
      - name: Publish app
        working-directory: app
        run: |
          yarn install
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn expo login --non-interactive -u ${{ env.EXPO_USERNAME }} -p ${{ env.EXPO_PASSWORD }}
          yarn expo publish --non-interactive
  
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install and setup env
        run: |
          pip install ansible boto
          .github/actions/setenv/entrypoint.sh
      - name: Build API
        uses: docker/build-push-action@v1
        with:
          path: ./api
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_api
          tags: latest
      - name: Build Back-office
        uses: docker/build-push-action@v1
        with:
          path: ./back-office
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/madu_back-office
          build_args: REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: latest
      - name: Deploy
        working-directory: automation/ansible
        run: |
          echo $SSH_PRIVATE_KEY > id_rsa
          chmod 600 id_rsa
          ansible-galaxy install -r requirements.yml
          chmod 777 inventory/ec2.py
          ansible-playbook -i inventory/ec2.py staging.yml --tags deploy -u ubuntu --key id_rsa
